// <auto-generated />
using System;
using LoginRegisterApp.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginRegisterApp.Migrations.Tools
{
    [DbContext(typeof(ToolsContext))]
    partial class ToolsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoginRegisterApp.Models.Tools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWaiting")
                        .HasColumnType("bit");

                    b.Property<string>("MalwareResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ToolImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ToolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToolPrice")
                        .HasColumnType("int");

                    b.Property<string>("ToolSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tools");
                });
#pragma warning restore 612, 618
        }
    }
}
